FROM nginx:alpine

RUN addgroup -S nginxuser && adduser -S nginxuser -G nginxuser

COPY nginx/phonebiz.conf /etc/nginx/conf.d/default.conf
COPY frontend/dist /usr/share/nginx/html

RUN chown -R nginxuser:nginxuser /usr/share/nginx/html && \
    chown -R nginxuser:nginxuser /var/cache/nginx && \
    chown -R nginxuser:nginxuser /var/log/nginx && \
    chown -R nginxuser:nginxuser /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown -R nginxuser:nginxuser /var/run/nginx.pid

USER nginxuser

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
