-- V40: 修复 DECIMAL 精度不一致 (bill_raw 5个字段 10,2→12,2)
-- 铁律3: 金额用 DECIMAL(12,2)

ALTER TABLE bill_raw MODIFY COLUMN total_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '总金额';
ALTER TABLE bill_raw MODIFY COLUMN call_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '通话金额';
ALTER TABLE bill_raw MODIFY COLUMN data_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '流量金额';
ALTER TABLE bill_raw MODIFY COLUMN sms_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '短信金额';
ALTER TABLE bill_raw MODIFY COLUMN other_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '其他金额';
