-- V76: 三次分摊记录表
CREATE TABLE fee_allocation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    bill_month VARCHAR(7) NOT NULL COMMENT '账单月份 2026-05',
    allocation_level TINYINT NOT NULL COMMENT '分摊层级: 1=一次分摊 2=二次分摊 3=三次分摊',
    parent_org_id BIGINT COMMENT '上级组织ID: L1=集团 L2=一级分行 L3=二级分行',
    parent_org_name VARCHAR(200) COMMENT '上级组织名称',
    org_id BIGINT NOT NULL COMMENT '目标组织ID',
    org_name VARCHAR(200) NOT NULL COMMENT '目标组织名称',
    org_type TINYINT COMMENT '组织类型: 2=分行 3=部门 4=综合支行 5=零专支行',
    phone_count INT DEFAULT 0 COMMENT '号码数量',
    platform_usage_fee DECIMAL(12,2) DEFAULT 0 COMMENT '平台使用费',
    number_monthly_rent DECIMAL(12,2) DEFAULT 0 COMMENT '月租费',
    domestic_charge DECIMAL(12,2) DEFAULT 0 COMMENT '国内通话费',
    international_charge DECIMAL(12,2) DEFAULT 0 COMMENT '国际通话费',
    recording_fee DECIMAL(12,2) DEFAULT 0 COMMENT '录音费',
    ringtone_fee DECIMAL(12,2) DEFAULT 0 COMMENT '彩铃费',
    flash_sms_fee DECIMAL(12,2) DEFAULT 0 COMMENT '闪信费',
    total_amount DECIMAL(12,2) DEFAULT 0 COMMENT '费用合计',
    percentage DECIMAL(5,2) COMMENT '占上级费用比例%',
    status TINYINT DEFAULT 0 COMMENT '0=待确认 1=已确认 2=已驳回',
    confirmed_by VARCHAR(100) COMMENT '确认人',
    confirmed_at DATETIME COMMENT '确认时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    UNIQUE INDEX uk_alloc (bill_month, allocation_level, org_id),
    INDEX idx_parent (parent_org_id, bill_month),
    INDEX idx_bill_level (bill_month, allocation_level)
) COMMENT='费用分摊记录表 (三级分摊)';
